#!/bin/sh

sxhkd &

compton --config /home/ross/.config/compton/compton.conf &
feh --bg-fill /home/ross/Pictures/city.jpg &
wmname LG3D &

#Second monitor configuration
#Must be executed before the polybar command
if [ -x /usr/bin/bspwm_dual_monitor ];then
    bspwm_dual_monitor
fi
~/.config/polybar/launch.sh &

#Enable tapping and Natural Scrolling on Touchpad
xinput set-prop "DELL0810:00 044E:120A Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "DELL0810:00 044E:120A Touchpad" "libinput Natural Scrolling Enabled" 1

#Set keyboard layout to latam
setxkbmap -layout latam

#Defines workspaces for dual monitor
bspc monitor eDP1 -d zsh Firefox Code Spotify V
bspc monitor HDMI1 -d VI VII VIII IX X

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config border_width         2
bspc config window_gap          8
bspc config normal_border_color "#004070"
bspc config focused_border_color "#1F94F0" 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
