#! /bin/sh

sxhkd &

compton --config /home/ross/.config/compton/compton.conf &
feh --bg-fill /home/ross/Pictures/city.jpg &
wmname LG 3D &
~/.config/polybar/launch.sh &

#Enable tapping on Touchpad
xinput set-prop 12 331 1

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc monitor -d zsh Firefox Code Spotify V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
